### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by AmainiRU**
icon_22

### CODE REVIEW

**Comment by YoCodingMonster** [comment]
thanks for the contribution!!

**Comment by ulgens** [comment]
@YoCodingMonster What happened in this PR? It does many things except changing an icon.

**Comment by YoCodingMonster** [comment]
i did merge it on purpose to do many other things, but didnt check on the icon🥲

**Comment by ulgens** [comment]
> i did merge it on purpose to do many other things,

If this is the case, can you please update the PR title and body? Having base OS changed in "new icon" PR is a bit confusing for outsiders. Thank you 🌷

**Pull request merged**
